
create table animal (
  species                       varchar(255) not null,
  id                            bigint generated by default as identity not null,
  shelter_id                    bigint,
  version                       bigint not null,
  name                          varchar(255),
  registration_number           varchar(255),
  date_of_birth                 date,
  dog_size                      varchar(255),
  constraint pk_animal primary key (id)
);

create table animal_shelter (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  version                       bigint not null,
  constraint pk_animal_shelter primary key (id)
);
