
delimiter $$
BEGIN 
IF (NOT exists (SELECT * FROM SYSIBM.SYSTABLESPACES WHERE TBSPACE = 'TSTABLES')) THEN 
EXECUTE IMMEDIATE 'CREATE TABLESPACE "TSTABLES"';
END IF;
END
$$
delimiter $$
BEGIN 
IF (NOT exists (SELECT * FROM SYSIBM.SYSTABLESPACES WHERE TBSPACE = 'INDEXTS')) 
THEN EXECUTE IMMEDIATE 'CREATE TABLESPACE "INDEXTS"';
END IF;
END
$$
delimiter $$
BEGIN 
IF (NOT exists (SELECT * FROM SYSIBM.SYSTABLESPACES WHERE TBSPACE = 'TESTTS')) THEN 
EXECUTE IMMEDIATE 'CREATE TABLESPACE "TESTTS"';
END IF;
END
$$
delimiter $$
BEGIN 
IF (NOT exists (SELECT * FROM SYSIBM.SYSTABLESPACES WHERE TBSPACE = 'TSMASTER')) THEN 
EXECUTE IMMEDIATE 'CREATE TABLESPACE "TSMASTER"';
END IF;
END
$$
