-- Generated by ebean unknown at 2020-08-24T21:02:32.420817Z
alter table if exists bar drop constraint if exists fk_bar_foo_id;
drop index if exists ix_bar_foo_id;

alter table if exists acl_container_relation drop constraint if exists fk_acl_container_relation_container_id;
drop index if exists ix_acl_container_relation_container_id;

alter table if exists acl_container_relation drop constraint if exists fk_acl_container_relation_acl_entry_id;
drop index if exists ix_acl_container_relation_acl_entry_id;

alter table if exists addr drop constraint if exists fk_addr_employee_id;
drop index if exists ix_addr_employee_id;

alter table if exists o_address drop constraint if exists fk_o_address_country_code;
drop index if exists ix_o_address_country_code;

alter table if exists album drop constraint if exists fk_album_cover_id;

alter table if exists animal drop constraint if exists fk_animal_shelter_id;
drop index if exists ix_animal_shelter_id;

alter table if exists attribute drop constraint if exists fk_attribute_attribute_holder_id;
drop index if exists ix_attribute_attribute_holder_id;

alter table if exists bbookmark drop constraint if exists fk_bbookmark_user_id;
drop index if exists ix_bbookmark_user_id;

alter table if exists bbookmark_user drop constraint if exists fk_bbookmark_user_org_id;
drop index if exists ix_bbookmark_user_org_id;

alter table if exists bsite_user_a drop constraint if exists fk_bsite_user_a_site_id;
drop index if exists ix_bsite_user_a_site_id;

alter table if exists bsite_user_a drop constraint if exists fk_bsite_user_a_user_id;
drop index if exists ix_bsite_user_a_user_id;

alter table if exists bsite_user_b drop constraint if exists fk_bsite_user_b_site;
drop index if exists ix_bsite_user_b_site;

alter table if exists bsite_user_b drop constraint if exists fk_bsite_user_b_usr;
drop index if exists ix_bsite_user_b_usr;

alter table if exists bsite_user_c drop constraint if exists fk_bsite_user_c_site_uid;
drop index if exists ix_bsite_user_c_site_uid;

alter table if exists bsite_user_c drop constraint if exists fk_bsite_user_c_user_uid;
drop index if exists ix_bsite_user_c_user_uid;

alter table if exists bsite_user_e drop constraint if exists fk_bsite_user_e_site_id;
drop index if exists ix_bsite_user_e_site_id;

alter table if exists bsite_user_e drop constraint if exists fk_bsite_user_e_user_id;
drop index if exists ix_bsite_user_e_user_id;

alter table if exists basic_draftable_bean drop constraint if exists fk_basic_draftable_bean_id;

alter table if exists drel_booking drop constraint if exists fk_drel_booking_agent_invoice;

alter table if exists drel_booking drop constraint if exists fk_drel_booking_client_invoice;

alter table if exists cepproduct_category drop constraint if exists fk_cepproduct_category_category_id;
drop index if exists ix_cepproduct_category_category_id;

alter table if exists cepproduct_category drop constraint if exists fk_cepproduct_category_product_id;
drop index if exists ix_cepproduct_category_product_id;

alter table if exists ciaddress drop constraint if exists fk_ciaddress_street_id;
drop index if exists ix_ciaddress_street_id;

alter table if exists cicustomer_parent drop constraint if exists fk_cicustomer_parent_address_id;
drop index if exists ix_cicustomer_parent_address_id;

alter table if exists cinh_ref drop constraint if exists fk_cinh_ref_ref_id;
drop index if exists ix_cinh_ref_ref_id;

alter table if exists ckey_detail drop constraint if exists fk_ckey_detail_parent;
drop index if exists ix_ckey_detail_parent;

alter table if exists ckey_parent drop constraint if exists fk_ckey_parent_assoc_id;
drop index if exists ix_ckey_parent_assoc_id;

alter table if exists coone_many drop constraint if exists fk_coone_many_coone_id;
drop index if exists ix_coone_many_coone_id;

alter table if exists coroot drop constraint if exists fk_coroot_one_id;

alter table if exists calculation_result drop constraint if exists fk_calculation_result_product_configuration_id;
drop index if exists ix_calculation_result_product_configuration_id;

alter table if exists calculation_result drop constraint if exists fk_calculation_result_group_configuration_id;
drop index if exists ix_calculation_result_group_configuration_id;

alter table if exists sp_car_car_wheels drop constraint if exists fk_sp_car_car_wheels_sp_car_car;
drop index if exists ix_sp_car_car_wheels_sp_car_car;

alter table if exists sp_car_car_wheels drop constraint if exists fk_sp_car_car_wheels_sp_car_wheel;
drop index if exists ix_sp_car_car_wheels_sp_car_wheel;

alter table if exists sp_car_car_doors drop constraint if exists fk_sp_car_car_doors_sp_car_car;
drop index if exists ix_sp_car_car_doors_sp_car_car;

alter table if exists sp_car_car_doors drop constraint if exists fk_sp_car_car_doors_sp_car_door;
drop index if exists ix_sp_car_car_doors_sp_car_door;

alter table if exists car_accessory drop constraint if exists fk_car_accessory_fuse_id;
drop index if exists ix_car_accessory_fuse_id;

alter table if exists car_accessory drop constraint if exists fk_car_accessory_car_id;
drop index if exists ix_car_accessory_car_id;

alter table if exists category drop constraint if exists fk_category_surveyobjectid;
drop index if exists ix_category_surveyobjectid;

alter table if exists e_save_test_d drop constraint if exists fk_e_save_test_d_parent_id;

alter table if exists child_person drop constraint if exists fk_child_person_some_bean_id;
drop index if exists ix_child_person_some_bean_id;

alter table if exists child_person drop constraint if exists fk_child_person_parent_identifier;
drop index if exists ix_child_person_parent_identifier;

alter table if exists cke_client drop constraint if exists fk_cke_client_user;
drop index if exists ix_cke_client_user;

alter table if exists class_super_monkey drop constraint if exists fk_class_super_monkey_class_super;

alter table if exists class_super_monkey drop constraint if exists fk_class_super_monkey_monkey;

alter table if exists configuration drop constraint if exists fk_configuration_configurations_id;
drop index if exists ix_configuration_configurations_id;

alter table if exists contact drop constraint if exists fk_contact_customer_id;
drop index if exists ix_contact_customer_id;

alter table if exists contact drop constraint if exists fk_contact_group_id;
drop index if exists ix_contact_group_id;

alter table if exists contact_note drop constraint if exists fk_contact_note_contact_id;
drop index if exists ix_contact_note_contact_id;

alter table if exists contract_costs drop constraint if exists fk_contract_costs_position_id;
drop index if exists ix_contract_costs_position_id;

alter table if exists c_conversation drop constraint if exists fk_c_conversation_group_id;
drop index if exists ix_c_conversation_group_id;

alter table if exists o_customer drop constraint if exists fk_o_customer_billing_address_id;
drop index if exists ix_o_customer_billing_address_id;

alter table if exists o_customer drop constraint if exists fk_o_customer_shipping_address_id;
drop index if exists ix_o_customer_shipping_address_id;

alter table if exists dcredit_drol drop constraint if exists fk_dcredit_drol_dcredit;
drop index if exists ix_dcredit_drol_dcredit;

alter table if exists dcredit_drol drop constraint if exists fk_dcredit_drol_drol;
drop index if exists ix_dcredit_drol_drol;

alter table if exists dmachine drop constraint if exists fk_dmachine_organisation_id;
drop index if exists ix_dmachine_organisation_id;

alter table if exists d_machine_aux_use drop constraint if exists fk_d_machine_aux_use_machine_id;
drop index if exists ix_d_machine_aux_use_machine_id;

alter table if exists d_machine_stats drop constraint if exists fk_d_machine_stats_machine_id;
drop index if exists ix_d_machine_stats_machine_id;

alter table if exists d_machine_use drop constraint if exists fk_d_machine_use_machine_id;
drop index if exists ix_d_machine_use_machine_id;

alter table if exists drot_drol drop constraint if exists fk_drot_drol_drot;
drop index if exists ix_drot_drol_drot;

alter table if exists drot_drol drop constraint if exists fk_drot_drol_drol;
drop index if exists ix_drot_drol_drol;

alter table if exists dc_detail drop constraint if exists fk_dc_detail_master_id;
drop index if exists ix_dc_detail_master_id;

alter table if exists defaults_model drop constraint if exists fk_defaults_model_id;

alter table if exists dfk_cascade drop constraint if exists fk_dfk_cascade_one_id;
drop index if exists ix_dfk_cascade_one_id;

alter table if exists dfk_set_null drop constraint if exists fk_dfk_set_null_one_id;
drop index if exists ix_dfk_set_null_one_id;

alter table if exists doc drop constraint if exists fk_doc_id;

alter table if exists doc_link drop constraint if exists fk_doc_link_doc;
drop index if exists ix_doc_link_doc;

alter table if exists doc_link drop constraint if exists fk_doc_link_link;
drop index if exists ix_doc_link_link;

alter table if exists document drop constraint if exists fk_document_id;

alter table if exists document drop constraint if exists fk_document_organisation_id;
drop index if exists ix_document_organisation_id;

alter table if exists document_draft drop constraint if exists fk_document_draft_organisation_id;
drop index if exists ix_document_draft_organisation_id;

alter table if exists document_media drop constraint if exists fk_document_media_document_id;
drop index if exists ix_document_media_document_id;

alter table if exists document_media_draft drop constraint if exists fk_document_media_draft_document_id;
drop index if exists ix_document_media_draft_document_id;

alter table if exists e_basicenc_relate drop constraint if exists fk_e_basicenc_relate_other_id;
drop index if exists ix_e_basicenc_relate_other_id;

alter table if exists ebasic_json_map_detail drop constraint if exists fk_ebasic_json_map_detail_owner_id;
drop index if exists ix_ebasic_json_map_detail_owner_id;

alter table if exists ebasic_no_sdchild drop constraint if exists fk_ebasic_no_sdchild_owner_id;
drop index if exists ix_ebasic_no_sdchild_owner_id;

alter table if exists ebasic_sdchild drop constraint if exists fk_ebasic_sdchild_owner_id;
drop index if exists ix_ebasic_sdchild_owner_id;

alter table if exists ecache_child drop constraint if exists fk_ecache_child_root_id;
drop index if exists ix_ecache_child_root_id;

alter table if exists edefault_prop drop constraint if exists fk_edefault_prop_e_simple_usertypeid;

alter table if exists eemb_inner drop constraint if exists fk_eemb_inner_outer_id;
drop index if exists ix_eemb_inner_outer_id;

alter table if exists einvoice drop constraint if exists fk_einvoice_person_id;
drop index if exists ix_einvoice_person_id;

alter table if exists enull_collection_detail drop constraint if exists fk_enull_collection_detail_enull_collection_id;
drop index if exists ix_enull_collection_detail_enull_collection_id;

alter table if exists eopt_one_a drop constraint if exists fk_eopt_one_a_b_id;
drop index if exists ix_eopt_one_a_b_id;

alter table if exists eopt_one_b drop constraint if exists fk_eopt_one_b_c_id;
drop index if exists ix_eopt_one_b_c_id;

alter table if exists eper_addr drop constraint if exists fk_eper_addr_ma_country_code;
drop index if exists ix_eper_addr_ma_country_code;

alter table if exists esoft_del_book drop constraint if exists fk_esoft_del_book_lend_by_id;
drop index if exists ix_esoft_del_book_lend_by_id;

alter table if exists esoft_del_book_esoft_del_user drop constraint if exists fk_esoft_del_book_esoft_del_user_esoft_del_book;
drop index if exists ix_esoft_del_book_esoft_del_user_esoft_del_book;

alter table if exists esoft_del_book_esoft_del_user drop constraint if exists fk_esoft_del_book_esoft_del_user_esoft_del_user;
drop index if exists ix_esoft_del_book_esoft_del_user_esoft_del_user;

alter table if exists esoft_del_down drop constraint if exists fk_esoft_del_down_esoft_del_mid_id;
drop index if exists ix_esoft_del_down_esoft_del_mid_id;

alter table if exists esoft_del_mid drop constraint if exists fk_esoft_del_mid_top_id;
drop index if exists ix_esoft_del_mid_top_id;

alter table if exists esoft_del_mid drop constraint if exists fk_esoft_del_mid_up_id;
drop index if exists ix_esoft_del_mid_up_id;

alter table if exists esoft_del_one_a drop constraint if exists fk_esoft_del_one_a_oneb_id;

alter table if exists esoft_del_role_esoft_del_user drop constraint if exists fk_esoft_del_role_esoft_del_user_esoft_del_role;
drop index if exists ix_esoft_del_role_esoft_del_user_esoft_del_role;

alter table if exists esoft_del_role_esoft_del_user drop constraint if exists fk_esoft_del_role_esoft_del_user_esoft_del_user;
drop index if exists ix_esoft_del_role_esoft_del_user_esoft_del_user;

alter table if exists esoft_del_user_esoft_del_role drop constraint if exists fk_esoft_del_user_esoft_del_role_esoft_del_user;
drop index if exists ix_esoft_del_user_esoft_del_role_esoft_del_user;

alter table if exists esoft_del_user_esoft_del_role drop constraint if exists fk_esoft_del_user_esoft_del_role_esoft_del_role;
drop index if exists ix_esoft_del_user_esoft_del_role_esoft_del_role;

alter table if exists rawinherit_uncle drop constraint if exists fk_rawinherit_uncle_parent_id;
drop index if exists ix_rawinherit_uncle_parent_id;

alter table if exists evanilla_collection_detail drop constraint if exists fk_evanilla_collection_detail_evanilla_collection_id;
drop index if exists ix_evanilla_collection_detail_evanilla_collection_id;

alter table if exists ec_enum_person_tags drop constraint if exists fk_ec_enum_person_tags_ec_enum_person_id;
drop index if exists ix_ec_enum_person_tags_ec_enum_person_id;

alter table if exists ec_person_phone drop constraint if exists fk_ec_person_phone_owner_id;
drop index if exists ix_ec_person_phone_owner_id;

alter table if exists ec_top drop constraint if exists fk_ec_top_person_id;
drop index if exists ix_ec_top_person_id;

alter table if exists ec_top_ecs_person drop constraint if exists fk_ec_top_ecs_person_ec_top;
drop index if exists ix_ec_top_ecs_person_ec_top;

alter table if exists ec_top_ecs_person drop constraint if exists fk_ec_top_ecs_person_ecs_person;
drop index if exists ix_ec_top_ecs_person_ecs_person;

alter table if exists ecbl_person_phone_numbers drop constraint if exists fk_ecbl_person_phone_numbers_person_id;
drop index if exists ix_ecbl_person_phone_numbers_person_id;

alter table if exists ecbm_person_phone_numbers drop constraint if exists fk_ecbm_person_phone_numbers_person_id;
drop index if exists ix_ecbm_person_phone_numbers_person_id;

alter table if exists ecm_person_phone_numbers drop constraint if exists fk_ecm_person_phone_numbers_ecm_person_id;
drop index if exists ix_ecm_person_phone_numbers_ecm_person_id;

alter table if exists ecmc_person_phone_numbers drop constraint if exists fk_ecmc_person_phone_numbers_ecmc_person_id;
drop index if exists ix_ecmc_person_phone_numbers_ecmc_person_id;

alter table if exists ecs_person_phone drop constraint if exists fk_ecs_person_phone_ecs_person_id;
drop index if exists ix_ecs_person_phone_ecs_person_id;

alter table if exists ecsm_child drop constraint if exists fk_ecsm_child_ecsm_parent_id;
drop index if exists ix_ecsm_child_ecsm_parent_id;

alter table if exists td_child drop constraint if exists fk_td_child_parent_id;
drop index if exists ix_td_child_parent_id;

alter table if exists element_bean drop constraint if exists fk_element_bean_complex_bean_id;
drop index if exists ix_element_bean_complex_bean_id;

alter table if exists empl drop constraint if exists fk_empl_default_address_id;
drop index if exists ix_empl_default_address_id;

alter table if exists esd_detail drop constraint if exists fk_esd_detail_master_id;
drop index if exists ix_esd_detail_master_id;

alter table if exists grand_parent_person drop constraint if exists fk_grand_parent_person_some_bean_id;
drop index if exists ix_grand_parent_person_some_bean_id;

alter table if exists survey_group drop constraint if exists fk_survey_group_categoryobjectid;
drop index if exists ix_survey_group_categoryobjectid;

alter table if exists hx_link_doc drop constraint if exists fk_hx_link_doc_hx_link;
drop index if exists ix_hx_link_doc_hx_link;

alter table if exists hx_link_doc drop constraint if exists fk_hx_link_doc_he_doc;
drop index if exists ix_hx_link_doc_he_doc;

alter table if exists hi_link_doc drop constraint if exists fk_hi_link_doc_hi_link;
drop index if exists ix_hi_link_doc_hi_link;

alter table if exists hi_link_doc drop constraint if exists fk_hi_link_doc_hi_doc;
drop index if exists ix_hi_link_doc_hi_doc;

alter table if exists hi_tthree drop constraint if exists fk_hi_tthree_hi_ttwo_id;
drop index if exists ix_hi_tthree_hi_ttwo_id;

alter table if exists hi_ttwo drop constraint if exists fk_hi_ttwo_hi_tone_id;
drop index if exists ix_hi_ttwo_hi_tone_id;

alter table if exists hsd_setting drop constraint if exists fk_hsd_setting_user_id;

alter table if exists iaf_segment drop constraint if exists fk_iaf_segment_status_id;
drop index if exists ix_iaf_segment_status_id;

alter table if exists imrelated drop constraint if exists fk_imrelated_owner_id;
drop index if exists ix_imrelated_owner_id;

alter table if exists info_contact drop constraint if exists fk_info_contact_company_id;
drop index if exists ix_info_contact_company_id;

alter table if exists info_customer drop constraint if exists fk_info_customer_company_id;

alter table if exists inner_report drop constraint if exists fk_inner_report_forecast_id;

alter table if exists drel_invoice drop constraint if exists fk_drel_invoice_booking;
drop index if exists ix_drel_invoice_booking;

alter table if exists item drop constraint if exists fk_item_etype;
drop index if exists ix_item_etype;

alter table if exists item drop constraint if exists fk_item_eregion;
drop index if exists ix_item_eregion;

alter table if exists mkeygroup_monkey drop constraint if exists fk_mkeygroup_monkey_mkeygroup;

alter table if exists mkeygroup_monkey drop constraint if exists fk_mkeygroup_monkey_monkey;

alter table if exists trainer_monkey drop constraint if exists fk_trainer_monkey_trainer;

alter table if exists trainer_monkey drop constraint if exists fk_trainer_monkey_monkey;

alter table if exists troop_monkey drop constraint if exists fk_troop_monkey_troop;

alter table if exists troop_monkey drop constraint if exists fk_troop_monkey_monkey;

alter table if exists l2_cldf_reset_bean_child drop constraint if exists fk_l2_cldf_reset_bean_child_parent_id;
drop index if exists ix_l2_cldf_reset_bean_child_parent_id;

alter table if exists level1_level4 drop constraint if exists fk_level1_level4_level1;
drop index if exists ix_level1_level4_level1;

alter table if exists level1_level4 drop constraint if exists fk_level1_level4_level4;
drop index if exists ix_level1_level4_level4;

alter table if exists level1_level2 drop constraint if exists fk_level1_level2_level1;
drop index if exists ix_level1_level2_level1;

alter table if exists level1_level2 drop constraint if exists fk_level1_level2_level2;
drop index if exists ix_level1_level2_level2;

alter table if exists level2_level3 drop constraint if exists fk_level2_level3_level2;
drop index if exists ix_level2_level3_level2;

alter table if exists level2_level3 drop constraint if exists fk_level2_level3_level3;
drop index if exists ix_level2_level3_level3;

alter table if exists link drop constraint if exists fk_link_id;

alter table if exists la_attr_value_attribute drop constraint if exists fk_la_attr_value_attribute_la_attr_value;
drop index if exists ix_la_attr_value_attribute_la_attr_value;

alter table if exists la_attr_value_attribute drop constraint if exists fk_la_attr_value_attribute_attribute;
drop index if exists ix_la_attr_value_attribute_attribute;

alter table if exists looney drop constraint if exists fk_looney_tune_id;
drop index if exists ix_looney_tune_id;

alter table if exists mcontact drop constraint if exists fk_mcontact_customer_id;
drop index if exists ix_mcontact_customer_id;

alter table if exists mcontact_message drop constraint if exists fk_mcontact_message_contact_id;
drop index if exists ix_mcontact_message_contact_id;

alter table if exists mcustomer drop constraint if exists fk_mcustomer_shipping_address_id;
drop index if exists ix_mcustomer_shipping_address_id;

alter table if exists mcustomer drop constraint if exists fk_mcustomer_billing_address_id;
drop index if exists ix_mcustomer_billing_address_id;

alter table if exists mmachine_mgroup drop constraint if exists fk_mmachine_mgroup_mmachine;
drop index if exists ix_mmachine_mgroup_mmachine;

alter table if exists mmachine_mgroup drop constraint if exists fk_mmachine_mgroup_mgroup;
drop index if exists ix_mmachine_mgroup_mgroup;

alter table if exists mprinter drop constraint if exists fk_mprinter_current_state_id;
drop index if exists ix_mprinter_current_state_id;

alter table if exists mprinter drop constraint if exists fk_mprinter_last_swap_cyan_id;

alter table if exists mprinter drop constraint if exists fk_mprinter_last_swap_magenta_id;

alter table if exists mprinter drop constraint if exists fk_mprinter_last_swap_yellow_id;

alter table if exists mprinter drop constraint if exists fk_mprinter_last_swap_black_id;

alter table if exists mprinter_state drop constraint if exists fk_mprinter_state_printer_id;
drop index if exists ix_mprinter_state_printer_id;

alter table if exists mprofile drop constraint if exists fk_mprofile_picture_id;
drop index if exists ix_mprofile_picture_id;

alter table if exists mrole_muser drop constraint if exists fk_mrole_muser_mrole;
drop index if exists ix_mrole_muser_mrole;

alter table if exists mrole_muser drop constraint if exists fk_mrole_muser_muser;
drop index if exists ix_mrole_muser_muser;

alter table if exists muser drop constraint if exists fk_muser_user_type_id;
drop index if exists ix_muser_user_type_id;

alter table if exists mail_user_inbox drop constraint if exists fk_mail_user_inbox_mail_user;
drop index if exists ix_mail_user_inbox_mail_user;

alter table if exists mail_user_inbox drop constraint if exists fk_mail_user_inbox_mail_box;
drop index if exists ix_mail_user_inbox_mail_box;

alter table if exists mail_user_outbox drop constraint if exists fk_mail_user_outbox_mail_user;
drop index if exists ix_mail_user_outbox_mail_user;

alter table if exists mail_user_outbox drop constraint if exists fk_mail_user_outbox_mail_box;
drop index if exists ix_mail_user_outbox_mail_box;

alter table if exists c_message drop constraint if exists fk_c_message_conversation_id;
drop index if exists ix_c_message_conversation_id;

alter table if exists c_message drop constraint if exists fk_c_message_user_id;
drop index if exists ix_c_message_user_id;

alter table if exists meter_contract_data drop constraint if exists fk_meter_contract_data_special_needs_client_id;

alter table if exists meter_special_needs_client drop constraint if exists fk_meter_special_needs_client_primary_id;

alter table if exists meter_version drop constraint if exists fk_meter_version_address_data_id;

alter table if exists meter_version drop constraint if exists fk_meter_version_contract_data_id;

alter table if exists mnoc_user_mnoc_role drop constraint if exists fk_mnoc_user_mnoc_role_mnoc_user;
drop index if exists ix_mnoc_user_mnoc_role_mnoc_user;

alter table if exists mnoc_user_mnoc_role drop constraint if exists fk_mnoc_user_mnoc_role_mnoc_role;
drop index if exists ix_mnoc_user_mnoc_role_mnoc_role;

alter table if exists mny_b drop constraint if exists fk_mny_b_a_id;
drop index if exists ix_mny_b_a_id;

alter table if exists mny_b_mny_c drop constraint if exists fk_mny_b_mny_c_mny_b;
drop index if exists ix_mny_b_mny_c_mny_b;

alter table if exists mny_b_mny_c drop constraint if exists fk_mny_b_mny_c_mny_c;
drop index if exists ix_mny_b_mny_c_mny_c;

alter table if exists subtopics drop constraint if exists fk_subtopics_mny_topic_1;
drop index if exists ix_subtopics_mny_topic_1;

alter table if exists subtopics drop constraint if exists fk_subtopics_mny_topic_2;
drop index if exists ix_subtopics_mny_topic_2;

alter table if exists mp_role drop constraint if exists fk_mp_role_mp_user_id;
drop index if exists ix_mp_role_mp_user_id;

alter table if exists ms_many_a_many_b drop constraint if exists fk_ms_many_a_many_b_ms_many_a;
drop index if exists ix_ms_many_a_many_b_ms_many_a;

alter table if exists ms_many_a_many_b drop constraint if exists fk_ms_many_a_many_b_ms_many_b;
drop index if exists ix_ms_many_a_many_b_ms_many_b;

alter table if exists ms_many_b_many_a drop constraint if exists fk_ms_many_b_many_a_ms_many_b;
drop index if exists ix_ms_many_b_many_a_ms_many_b;

alter table if exists ms_many_b_many_a drop constraint if exists fk_ms_many_b_many_a_ms_many_a;
drop index if exists ix_ms_many_b_many_a_ms_many_a;

alter table if exists my_lob_size_join_many drop constraint if exists fk_my_lob_size_join_many_parent_id;
drop index if exists ix_my_lob_size_join_many_parent_id;

alter table if exists o_bean_child drop constraint if exists fk_o_bean_child_cached_bean_id;
drop index if exists ix_o_bean_child_cached_bean_id;

alter table if exists ocached_app_detail drop constraint if exists fk_ocached_app_detail_app_id;
drop index if exists ix_ocached_app_detail_app_id;

alter table if exists o_cached_bean_country drop constraint if exists fk_o_cached_bean_country_o_cached_bean;
drop index if exists ix_o_cached_bean_country_o_cached_bean;

alter table if exists o_cached_bean_country drop constraint if exists fk_o_cached_bean_country_o_country;
drop index if exists ix_o_cached_bean_country_o_country;

alter table if exists o_cached_bean_child drop constraint if exists fk_o_cached_bean_child_cached_bean_id;
drop index if exists ix_o_cached_bean_child_cached_bean_id;

alter table if exists oengine drop constraint if exists fk_oengine_car_id;

alter table if exists ogear_box drop constraint if exists fk_ogear_box_car_id;

alter table if exists omvertex_other drop constraint if exists fk_omvertex_other_omvertex_id;
drop index if exists ix_omvertex_other_omvertex_id;

alter table if exists oroad_show_msg drop constraint if exists fk_oroad_show_msg_company_id;

alter table if exists om_account_child_dbo drop constraint if exists fk_om_account_child_dbo_banana_rama_id;
drop index if exists ix_om_account_child_dbo_banana_rama_id;

alter table if exists om_basic_child drop constraint if exists fk_om_basic_child_parent_id;
drop index if exists ix_om_basic_child_parent_id;

alter table if exists om_ordered_detail drop constraint if exists fk_om_ordered_detail_master_id;
drop index if exists ix_om_ordered_detail_master_id;

alter table if exists oml_baz drop constraint if exists fk_oml_baz_foo_id;
drop index if exists ix_oml_baz_foo_id;

alter table if exists oml_foo drop constraint if exists fk_oml_foo_bar_id;
drop index if exists ix_oml_foo_bar_id;

alter table if exists o_order drop constraint if exists fk_o_order_kcustomer_id;
drop index if exists ix_o_order_kcustomer_id;

alter table if exists o_order_detail drop constraint if exists fk_o_order_detail_order_id;
drop index if exists ix_o_order_detail_order_id;

alter table if exists o_order_detail drop constraint if exists fk_o_order_detail_product_id;
drop index if exists ix_o_order_detail_product_id;

alter table if exists s_order_items drop constraint if exists fk_s_order_items_order_uuid;
drop index if exists ix_s_order_items_order_uuid;

alter table if exists order_referenced_parent drop constraint if exists fk_order_referenced_parent_master_id;
drop index if exists ix_order_referenced_parent_master_id;

alter table if exists or_order_ship drop constraint if exists fk_or_order_ship_order_id;
drop index if exists ix_or_order_ship_order_id;

alter table if exists order_toy drop constraint if exists fk_order_toy_child_id;
drop index if exists ix_order_toy_child_id;

alter table if exists ordered_parent drop constraint if exists fk_ordered_parent_order_master_inheritance_id;
drop index if exists ix_ordered_parent_order_master_inheritance_id;

alter table if exists organization_node drop constraint if exists fk_organization_node_parent_tree_node_id;

alter table if exists orp_detail drop constraint if exists fk_orp_detail_master_id;
drop index if exists ix_orp_detail_master_id;

alter table if exists orp_detail2 drop constraint if exists fk_orp_detail2_orp_master2_id;
drop index if exists ix_orp_detail2_orp_master2_id;

alter table if exists oto_atwo drop constraint if exists fk_oto_atwo_aone_id;

alter table if exists oto_bchild drop constraint if exists fk_oto_bchild_master_id;

alter table if exists oto_child drop constraint if exists fk_oto_child_master_id;

alter table if exists oto_cust_address drop constraint if exists fk_oto_cust_address_customer_cid;

alter table if exists oto_level_a drop constraint if exists fk_oto_level_a_b_id;

alter table if exists oto_level_b drop constraint if exists fk_oto_level_b_c_id;

alter table if exists oto_prime_extra drop constraint if exists fk_oto_prime_extra_eid;

alter table if exists oto_sd_child drop constraint if exists fk_oto_sd_child_master_id;

alter table if exists oto_th_many drop constraint if exists fk_oto_th_many_oto_th_top_id;
drop index if exists ix_oto_th_many_oto_th_top_id;

alter table if exists oto_th_one drop constraint if exists fk_oto_th_one_many_id;

alter table if exists oto_ubprime_extra drop constraint if exists fk_oto_ubprime_extra_eid;

alter table if exists oto_user_model drop constraint if exists fk_oto_user_model_user_optional_id;

alter table if exists pfile drop constraint if exists fk_pfile_file_content_id;

alter table if exists pfile drop constraint if exists fk_pfile_file_content2_id;

alter table if exists paggview drop constraint if exists fk_paggview_pview_id;

alter table if exists pallet_location drop constraint if exists fk_pallet_location_zone_sid;
drop index if exists ix_pallet_location_zone_sid;

alter table if exists parcel_location drop constraint if exists fk_parcel_location_parcelid;

alter table if exists rawinherit_parent_rawinherit_data drop constraint if exists fk_rawinherit_parent_rawinherit_data_rawinherit_parent;
drop index if exists ix_rawinherit_parent_rawinherit_data_rawinherit_parent;

alter table if exists rawinherit_parent_rawinherit_data drop constraint if exists fk_rawinherit_parent_rawinherit_data_rawinherit_data;
drop index if exists ix_rawinherit_parent_rawinherit_data_rawinherit_data;

alter table if exists parent_person drop constraint if exists fk_parent_person_some_bean_id;
drop index if exists ix_parent_person_some_bean_id;

alter table if exists parent_person drop constraint if exists fk_parent_person_parent_identifier;
drop index if exists ix_parent_person_parent_identifier;

alter table if exists c_participation drop constraint if exists fk_c_participation_conversation_id;
drop index if exists ix_c_participation_conversation_id;

alter table if exists c_participation drop constraint if exists fk_c_participation_user_id;
drop index if exists ix_c_participation_user_id;

alter table if exists pcf_calendar drop constraint if exists fk_pcf_calendar_pcf_person_id;
drop index if exists ix_pcf_calendar_pcf_person_id;

alter table if exists pcf_city drop constraint if exists fk_pcf_city_pcf_country_id;
drop index if exists ix_pcf_city_pcf_country_id;

alter table if exists pcf_city drop constraint if exists fk_pcf_city_mayor_id;

alter table if exists pcf_city drop constraint if exists fk_pcf_city_vice_mayor_id;

alter table if exists pcf_event drop constraint if exists fk_pcf_event_pcf_calendar_id;
drop index if exists ix_pcf_event_pcf_calendar_id;

alter table if exists persistent_file_content drop constraint if exists fk_persistent_file_content_persistent_file_id;

alter table if exists person drop constraint if exists fk_person_default_address_oid;
drop index if exists ix_person_default_address_oid;

alter table if exists person_cache_email drop constraint if exists fk_person_cache_email_person_info_person_id;
drop index if exists ix_person_cache_email_person_info_person_id;

alter table if exists phones drop constraint if exists fk_phones_person_id;
drop index if exists ix_phones_person_id;

alter table if exists e_position drop constraint if exists fk_e_position_contract_id;
drop index if exists ix_e_position_contract_id;

alter table if exists pp_to_ww drop constraint if exists fk_pp_to_ww_pp;
drop index if exists ix_pp_to_ww_pp;

alter table if exists pp_to_ww drop constraint if exists fk_pp_to_ww_wview;
drop index if exists ix_pp_to_ww_wview;

alter table if exists question drop constraint if exists fk_question_groupobjectid;
drop index if exists ix_question_groupobjectid;

alter table if exists r_orders drop constraint if exists fk_r_orders_customer;
drop index if exists ix_r_orders_customer;

alter table if exists referenced_defaults_model drop constraint if exists fk_referenced_defaults_model_id;

alter table if exists referenced_defaults_model drop constraint if exists fk_referenced_defaults_model_defaults_model_id;
drop index if exists ix_referenced_defaults_model_defaults_model_id;

alter table if exists referenced_defaults_model_draft drop constraint if exists fk_referenced_defaults_model_draft_defaults_model_id;
drop index if exists ix_referenced_defaults_model_draft_defaults_model_id;

alter table if exists rel_master drop constraint if exists fk_rel_master_detail_id;
drop index if exists ix_rel_master_detail_id;

alter table if exists resourcefile drop constraint if exists fk_resourcefile_parentresourcefileid;
drop index if exists ix_resourcefile_parentresourcefileid;

alter table if exists mt_role drop constraint if exists fk_mt_role_tenant_id;
drop index if exists ix_mt_role_tenant_id;

alter table if exists mt_role_permission drop constraint if exists fk_mt_role_permission_mt_role;
drop index if exists ix_mt_role_permission_mt_role;

alter table if exists mt_role_permission drop constraint if exists fk_mt_role_permission_mt_permission;
drop index if exists ix_mt_role_permission_mt_permission;

alter table if exists root_bean drop constraint if exists fk_root_bean_referencing_bean_id;
drop index if exists ix_root_bean_referencing_bean_id;

alter table if exists f_second drop constraint if exists fk_f_second_first;

alter table if exists section drop constraint if exists fk_section_article_id;
drop index if exists ix_section_article_id;

alter table if exists self_parent drop constraint if exists fk_self_parent_parent_id;
drop index if exists ix_self_parent_parent_id;

alter table if exists self_ref_customer drop constraint if exists fk_self_ref_customer_referred_by_id;
drop index if exists ix_self_ref_customer_referred_by_id;

alter table if exists self_ref_example drop constraint if exists fk_self_ref_example_parent_id;
drop index if exists ix_self_ref_example_parent_id;

alter table if exists e_save_test_b drop constraint if exists fk_e_save_test_b_sibling_a_id;

alter table if exists site drop constraint if exists fk_site_parent_id;
drop index if exists ix_site_parent_id;

alter table if exists site drop constraint if exists fk_site_data_container_id;

alter table if exists site drop constraint if exists fk_site_site_address_id;

alter table if exists source_base drop constraint if exists fk_source_base_target_id;
drop index if exists ix_source_base_target_id;

alter table if exists stockforecast drop constraint if exists fk_stockforecast_inner_report_id;
drop index if exists ix_stockforecast_inner_report_id;

alter table if exists sub_section drop constraint if exists fk_sub_section_section_id;
drop index if exists ix_sub_section_section_id;

alter table if exists tevent_many drop constraint if exists fk_tevent_many_event_id;
drop index if exists ix_tevent_many_event_id;

alter table if exists tevent_one drop constraint if exists fk_tevent_one_event_id;

alter table if exists t_detail_with_other_namexxxyy drop constraint if exists fk_t_detail_with_other_namexxxyy_master_id;
drop index if exists ix_t_detail_with_other_namexxxyy_master_id;

alter table if exists ttruck_holder drop constraint if exists fk_ttruck_holder_truck_plate_no;
drop index if exists ix_ttruck_holder_truck_plate_no;

alter table if exists ttruck_holder drop constraint if exists fk_ttruck_holder_basic_id;
drop index if exists ix_ttruck_holder_basic_id;

alter table if exists ttruck_holder_item drop constraint if exists fk_ttruck_holder_item_owner_id;
drop index if exists ix_ttruck_holder_item_owner_id;

alter table if exists twheel drop constraint if exists fk_twheel_owner_plate_no;
drop index if exists ix_twheel_owner_plate_no;

alter table if exists tire drop constraint if exists fk_tire_wheel;

alter table if exists tree_entity drop constraint if exists fk_tree_entity_parent_id;
drop index if exists ix_tree_entity_parent_id;

alter table if exists trip drop constraint if exists fk_trip_vehicle_driver_id;
drop index if exists ix_trip_vehicle_driver_id;

alter table if exists trip drop constraint if exists fk_trip_address_id;
drop index if exists ix_trip_address_id;

alter table if exists "type" drop constraint if exists fk_type_sub_type_id;
drop index if exists ix_type_sub_type_id;

alter table if exists usib_child drop constraint if exists fk_usib_child_parent_id;
drop index if exists ix_usib_child_parent_id;

alter table if exists usib_child_sibling drop constraint if exists fk_usib_child_sibling_child_id;

alter table if exists ut_detail drop constraint if exists fk_ut_detail_utmaster_id;
drop index if exists ix_ut_detail_utmaster_id;

alter table if exists uutwo drop constraint if exists fk_uutwo_master_id;
drop index if exists ix_uutwo_master_id;

alter table if exists oto_user drop constraint if exists fk_oto_user_account_id;

alter table if exists c_user drop constraint if exists fk_c_user_group_id;
drop index if exists ix_c_user_group_id;

alter table if exists em_user_role drop constraint if exists fk_em_user_role_user_id;
drop index if exists ix_em_user_role_user_id;

alter table if exists em_user_role drop constraint if exists fk_em_user_role_role_id;
drop index if exists ix_em_user_role_role_id;

alter table if exists vehicle drop constraint if exists fk_vehicle_lease_id;
drop index if exists ix_vehicle_lease_id;

alter table if exists vehicle drop constraint if exists fk_vehicle_car_ref_id;
drop index if exists ix_vehicle_car_ref_id;

alter table if exists vehicle drop constraint if exists fk_vehicle_truck_ref_id;
drop index if exists ix_vehicle_truck_ref_id;

alter table if exists vehicle_driver drop constraint if exists fk_vehicle_driver_vehicle_id;
drop index if exists ix_vehicle_driver_vehicle_id;

alter table if exists vehicle_driver drop constraint if exists fk_vehicle_driver_address_id;
drop index if exists ix_vehicle_driver_address_id;

alter table if exists version_child drop constraint if exists fk_version_child_parent_id;
drop index if exists ix_version_child_parent_id;

alter table if exists version_toy drop constraint if exists fk_version_toy_child_id;
drop index if exists ix_version_toy_child_id;

alter table if exists warehouses drop constraint if exists fk_warehouses_officezoneid;
drop index if exists ix_warehouses_officezoneid;

alter table if exists warehousesshippingzones drop constraint if exists fk_warehousesshippingzones_warehouses;
drop index if exists ix_warehousesshippingzones_warehouses;

alter table if exists warehousesshippingzones drop constraint if exists fk_warehousesshippingzones_zones;
drop index if exists ix_warehousesshippingzones_zones;

alter table if exists sa_wheel drop constraint if exists fk_sa_wheel_tire;
drop index if exists ix_sa_wheel_tire;

alter table if exists sa_wheel drop constraint if exists fk_sa_wheel_car;
drop index if exists ix_sa_wheel_car;

alter table if exists g_who_props_otm drop constraint if exists fk_g_who_props_otm_who_created_id;
drop index if exists ix_g_who_props_otm_who_created_id;

alter table if exists g_who_props_otm drop constraint if exists fk_g_who_props_otm_who_modified_id;
drop index if exists ix_g_who_props_otm_who_modified_id;

alter table if exists with_zero drop constraint if exists fk_with_zero_parent_id;
drop index if exists ix_with_zero_parent_id;

drop table if exists asimple_bean cascade;

drop table if exists bar cascade;

drop table if exists block cascade;

drop table if exists oto_account cascade;

drop table if exists acl cascade;

drop table if exists acl_container_relation cascade;

drop table if exists addr cascade;

drop table if exists address cascade;

drop table if exists o_address cascade;

drop table if exists album cascade;

drop table if exists animal cascade;

drop table if exists animal_shelter cascade;

drop table if exists article cascade;

drop table if exists attribute cascade;

drop table if exists attribute_holder cascade;

drop table if exists audit_log cascade;

drop table if exists bbookmark cascade;

drop table if exists bbookmark_org cascade;

drop table if exists bbookmark_user cascade;

drop table if exists bsimple_with_gen cascade;

drop table if exists bsite cascade;

drop table if exists bsite_user_a cascade;

drop table if exists bsite_user_b cascade;

drop table if exists bsite_user_c cascade;

drop table if exists bsite_user_d cascade;

drop table if exists bsite_user_e cascade;

drop table if exists buser cascade;

drop table if exists bwith_qident cascade;

drop table if exists basic_draftable_bean cascade;

drop table if exists basic_draftable_bean_draft cascade;

drop table if exists basic_joda_entity cascade;

drop table if exists bean_with_time_zone cascade;

drop table if exists drel_booking cascade;
drop sequence if exists drel_booking_seq;

drop table if exists bw_bean cascade;

drop table if exists cepcategory cascade;

drop table if exists cepproduct cascade;

drop table if exists cepproduct_category cascade;

drop table if exists ciaddress cascade;

drop table if exists cicustomer_parent cascade;

drop table if exists cistreet_parent cascade;

drop table if exists cinh_ref cascade;

drop table if exists cinh_root cascade;

drop table if exists ckey_assoc cascade;

drop table if exists ckey_detail cascade;

drop table if exists ckey_parent cascade;

drop table if exists coone cascade;

drop table if exists coone_many cascade;

drop table if exists coroot cascade;

drop table if exists calculation_result cascade;

drop table if exists cao_bean cascade;

drop table if exists sp_car_car cascade;
drop sequence if exists sp_car_car_seq;

drop table if exists sp_car_car_wheels cascade;

drop table if exists sp_car_car_doors cascade;

drop table if exists sa_car cascade;
drop sequence if exists sa_car_seq;

drop table if exists car_accessory cascade;

drop table if exists car_fuse cascade;

drop table if exists category cascade;

drop table if exists e_save_test_d cascade;

drop table if exists child_person cascade;

drop table if exists cke_client cascade;

drop table if exists cke_user cascade;

drop table if exists class_super cascade;

drop table if exists class_super_monkey cascade;

drop table if exists configuration cascade;

drop table if exists configurations cascade;

drop table if exists contact cascade;

drop table if exists contact_group cascade;

drop table if exists contact_note cascade;

drop table if exists contract cascade;

drop table if exists contract_costs cascade;

drop table if exists c_conversation cascade;

drop table if exists o_country cascade;

drop table if exists cover cascade;

drop table if exists o_customer cascade;

drop table if exists dcredit cascade;

drop table if exists dcredit_drol cascade;

drop table if exists dexh_entity cascade;

drop table if exists dint_parent cascade;

drop table if exists dmachine cascade;

drop table if exists d_machine_aux_use cascade;

drop table if exists d_machine_stats cascade;

drop table if exists d_machine_use cascade;

drop table if exists dorg cascade;

drop table if exists dperson cascade;

drop table if exists drol cascade;

drop table if exists drot cascade;

drop table if exists drot_drol cascade;

drop table if exists rawinherit_data cascade;

drop table if exists data_container cascade;

drop table if exists dc_detail cascade;

drop table if exists dc_master cascade;

drop table if exists defaults_model cascade;

drop table if exists defaults_model_draft cascade;

drop table if exists dfk_cascade cascade;

drop table if exists dfk_cascade_one cascade;

drop table if exists dfk_none cascade;

drop table if exists dfk_none_via_join cascade;

drop table if exists dfk_none_via_mto_m cascade;

drop table if exists dfk_none_via_mto_m_dfk_one cascade;

drop table if exists dfk_one cascade;

drop table if exists dfk_set_null cascade;

drop table if exists doc cascade;

drop table if exists doc_link cascade;

drop table if exists doc_link_draft cascade;

drop table if exists doc_draft cascade;

drop table if exists document cascade;

drop table if exists document_draft cascade;

drop table if exists document_media cascade;

drop table if exists document_media_draft cascade;

drop table if exists sp_car_door cascade;
drop sequence if exists sp_car_door_seq;

drop table if exists earray_bean cascade;

drop table if exists earray_set_bean cascade;

drop table if exists e_basic cascade;

drop table if exists ebasic_change_log cascade;

drop table if exists ebasic_clob cascade;

drop table if exists ebasic_clob_fetch_eager cascade;

drop table if exists ebasic_clob_no_ver cascade;

drop table if exists e_basicenc cascade;

drop table if exists e_basicenc_bin cascade;

drop table if exists e_basicenc_client cascade;

drop table if exists e_basicenc_relate cascade;

drop table if exists e_basic_enum_id cascade;

drop table if exists e_basic_eni cascade;

drop table if exists ebasic_hstore cascade;

drop table if exists ebasic_json_jackson cascade;

drop table if exists ebasic_json_jackson2 cascade;

drop table if exists ebasic_json_list cascade;

drop table if exists ebasic_json_map cascade;

drop table if exists ebasic_json_map_blob cascade;

drop table if exists ebasic_json_map_clob cascade;

drop table if exists ebasic_json_map_detail cascade;

drop table if exists ebasic_json_map_json_b cascade;

drop table if exists ebasic_json_map_varchar cascade;

drop table if exists ebasic_json_node cascade;

drop table if exists ebasic_json_node_blob cascade;

drop table if exists ebasic_json_node_json_b cascade;

drop table if exists ebasic_json_node_varchar cascade;

drop table if exists ebasic_json_unmapped cascade;

drop table if exists e_basic_ndc cascade;

drop table if exists ebasic_no_sdchild cascade;

drop table if exists ebasic_sdchild cascade;

drop table if exists ebasic_soft_delete cascade;

drop table if exists e_basicver cascade;

drop table if exists e_basic_withlife cascade;

drop table if exists e_basic_with_ex cascade;

drop table if exists e_basicverucon cascade;

drop table if exists ecache_child cascade;

drop table if exists ecache_root cascade;

drop table if exists e_col_ab cascade;

drop table if exists ecustom_id cascade;

drop table if exists edefault_prop cascade;

drop table if exists eemb_inner cascade;

drop table if exists eemb_outer cascade;

drop table if exists efile2_no_fk cascade;

drop table if exists efile_no_fk cascade;

drop table if exists efile_no_fk_euser_no_fk cascade;

drop table if exists efile_no_fk_euser_no_fk_soft_del cascade;

drop table if exists egen_props cascade;

drop table if exists eid_uid_bean cascade;

drop table if exists einvoice cascade;

drop table if exists e_main cascade;

drop table if exists enull_collection cascade;

drop table if exists enull_collection_detail cascade;

drop table if exists eopt_one_a cascade;

drop table if exists eopt_one_b cascade;

drop table if exists eopt_one_c cascade;

drop table if exists eper_addr cascade;

drop table if exists eperson cascade;

drop table if exists e_person_online cascade;

drop table if exists esimple cascade;

drop table if exists esoft_del_book cascade;

drop table if exists esoft_del_book_esoft_del_user cascade;

drop table if exists esoft_del_down cascade;

drop table if exists esoft_del_mid cascade;

drop table if exists esoft_del_one_a cascade;

drop table if exists esoft_del_one_b cascade;

drop table if exists esoft_del_role cascade;

drop table if exists esoft_del_role_esoft_del_user cascade;

drop table if exists esoft_del_top cascade;

drop table if exists esoft_del_up cascade;

drop table if exists esoft_del_user cascade;

drop table if exists esoft_del_user_esoft_del_role cascade;

drop table if exists esome_convert_type cascade;

drop table if exists esome_type cascade;

drop table if exists etrans_many cascade;

drop table if exists rawinherit_uncle cascade;

drop table if exists euser_no_fk cascade;

drop table if exists euser_no_fk_soft_del cascade;

drop table if exists evanilla_collection cascade;

drop table if exists evanilla_collection_detail cascade;

drop table if exists ewho_props cascade;

drop table if exists e_withinet cascade;

drop table if exists ec_enum_person cascade;

drop table if exists ec_enum_person_tags cascade;

drop table if exists ec_person cascade;

drop table if exists ec_person_phone cascade;

drop table if exists ec_top cascade;

drop table if exists ec_top_ecs_person cascade;

drop table if exists ecbl_person cascade;

drop table if exists ecbl_person_phone_numbers cascade;

drop table if exists ecbm_person cascade;

drop table if exists ecbm_person_phone_numbers cascade;

drop table if exists ecm_person cascade;

drop table if exists ecm_person_phone_numbers cascade;

drop table if exists ecmc_person cascade;

drop table if exists ecmc_person_phone_numbers cascade;

drop table if exists ecs_person cascade;

drop table if exists ecs_person_phone cascade;

drop table if exists ecsm_child cascade;

drop table if exists ecsm_values cascade;

drop table if exists ecsm_one cascade;

drop table if exists ecsm_parent cascade;

drop table if exists ecsm_two cascade;

drop table if exists td_child cascade;

drop table if exists td_parent cascade;

drop table if exists element_bean cascade;

drop table if exists empl cascade;

drop table if exists esd_detail cascade;

drop table if exists esd_master cascade;

drop table if exists feature_desc cascade;

drop table if exists f_first cascade;

drop table if exists foo cascade;

drop table if exists gen_key_identity cascade;

drop table if exists gen_key_sequence cascade;
drop sequence if exists SEQ_NAME;

drop table if exists grand_parent_person cascade;

drop table if exists survey_group cascade;

drop table if exists c_group cascade;

drop table if exists he_doc cascade;

drop trigger if exists hx_link_history_upd on hx_link cascade;
drop function if exists hx_link_history_version();

drop view hx_link_with_history;
alter table hx_link drop column sys_period;
drop table hx_link_history;

drop table if exists hx_link cascade;

drop table if exists hx_link_doc cascade;

drop table if exists hi_doc cascade;

drop trigger if exists hi_link_history_upd on hi_link cascade;
drop function if exists hi_link_history_version();

drop view hi_link_with_history;
alter table hi_link drop column sys_period;
drop table hi_link_history;

drop table if exists hi_link cascade;

drop trigger if exists hi_link_doc_history_upd on hi_link_doc cascade;
drop function if exists hi_link_doc_history_version();

drop view hi_link_doc_with_history;
alter table hi_link_doc drop column sys_period;
drop table hi_link_doc_history;

drop table if exists hi_link_doc cascade;

drop trigger if exists hi_tone_history_upd on hi_tone cascade;
drop function if exists hi_tone_history_version();

drop view hi_tone_with_history;
alter table hi_tone drop column sys_period;
drop table hi_tone_history;

drop table if exists hi_tone cascade;

drop trigger if exists hi_tthree_history_upd on hi_tthree cascade;
drop function if exists hi_tthree_history_version();

drop view hi_tthree_with_history;
alter table hi_tthree drop column sys_period;
drop table hi_tthree_history;

drop table if exists hi_tthree cascade;

drop trigger if exists hi_ttwo_history_upd on hi_ttwo cascade;
drop function if exists hi_ttwo_history_version();

drop view hi_ttwo_with_history;
alter table hi_ttwo drop column sys_period;
drop table hi_ttwo_history;

drop table if exists hi_ttwo cascade;

drop trigger if exists hsd_setting_history_upd on hsd_setting cascade;
drop function if exists hsd_setting_history_version();

drop view hsd_setting_with_history;
alter table hsd_setting drop column sys_period;
drop table hsd_setting_history;

drop table if exists hsd_setting cascade;

drop trigger if exists hsd_user_history_upd on hsd_user cascade;
drop function if exists hsd_user_history_version();

drop view hsd_user_with_history;
alter table hsd_user drop column sys_period;
drop table hsd_user_history;

drop table if exists hsd_user cascade;

drop table if exists iaf_segment cascade;

drop table if exists iaf_segment_status cascade;

drop table if exists imrelated cascade;

drop table if exists imroot cascade;

drop table if exists ixresource cascade;

drop table if exists info_company cascade;

drop table if exists info_contact cascade;

drop table if exists info_customer cascade;

drop table if exists inner_report cascade;

drop table if exists drel_invoice cascade;
drop sequence if exists drel_invoice_seq;

drop table if exists item cascade;

drop table if exists monkey cascade;

drop table if exists mkeygroup cascade;

drop table if exists mkeygroup_monkey cascade;

drop table if exists trainer cascade;

drop table if exists trainer_monkey cascade;

drop table if exists troop cascade;

drop table if exists troop_monkey cascade;

drop table if exists l2_cldf_reset_bean cascade;

drop table if exists l2_cldf_reset_bean_child cascade;

drop table if exists level1 cascade;

drop table if exists level1_level4 cascade;

drop table if exists level1_level2 cascade;

drop table if exists level2 cascade;

drop table if exists level2_level3 cascade;

drop table if exists level3 cascade;

drop table if exists level4 cascade;

drop trigger if exists link_history_upd on link cascade;
drop function if exists link_history_version();

drop view link_with_history;
alter table link drop column sys_period;
drop table link_history;

drop table if exists link cascade;

drop table if exists link_draft cascade;

drop table if exists la_attr_value cascade;

drop table if exists la_attr_value_attribute cascade;

drop table if exists looney cascade;

drop table if exists maddress cascade;

drop table if exists mcontact cascade;

drop table if exists mcontact_message cascade;

drop table if exists mcustomer cascade;

drop table if exists mgroup cascade;

drop table if exists mmachine cascade;

drop table if exists mmachine_mgroup cascade;

drop table if exists mmedia cascade;

drop table if exists non_updateprop cascade;

drop table if exists mprinter cascade;

drop table if exists mprinter_state cascade;

drop table if exists mprofile cascade;

drop table if exists mprotected_construct_bean cascade;

drop table if exists mrole cascade;

drop table if exists mrole_muser cascade;

drop table if exists msome_other cascade;

drop table if exists muser cascade;

drop table if exists muser_type cascade;

drop table if exists mail_box cascade;

drop table if exists mail_user cascade;

drop table if exists mail_user_inbox cascade;

drop table if exists mail_user_outbox cascade;

drop table if exists main_entity cascade;

drop table if exists main_entity_relation cascade;

drop table if exists map_super_actual cascade;

drop table if exists c_message cascade;

drop table if exists meter_address_data cascade;

drop table if exists meter_contract_data cascade;

drop table if exists meter_special_needs_client cascade;

drop table if exists meter_special_needs_contact cascade;

drop table if exists meter_version cascade;

drop table if exists mnoc_role cascade;

drop table if exists mnoc_user cascade;

drop table if exists mnoc_user_mnoc_role cascade;

drop table if exists mny_a cascade;

drop table if exists mny_b cascade;

drop table if exists mny_b_mny_c cascade;

drop table if exists mny_c cascade;

drop table if exists mny_topic cascade;

drop table if exists subtopics cascade;

drop table if exists mp_role cascade;

drop table if exists mp_user cascade;

drop table if exists ms_many_a cascade;

drop table if exists ms_many_a_many_b cascade;

drop table if exists ms_many_b cascade;

drop table if exists ms_many_b_many_a cascade;

drop table if exists my_lob_size cascade;

drop table if exists my_lob_size_join_many cascade;

drop table if exists noidbean cascade;

drop table if exists o_bean_child cascade;

drop table if exists ocached_app cascade;

drop table if exists ocached_app_detail cascade;

drop table if exists o_cached_bean cascade;

drop table if exists o_cached_bean_country cascade;

drop table if exists o_cached_bean_child cascade;

drop table if exists o_cached_inherit cascade;

drop table if exists o_cached_natkey cascade;

drop table if exists o_cached_natkey3 cascade;

drop table if exists ocached_nkey_uid cascade;

drop table if exists ocar cascade;

drop table if exists ocompany cascade;

drop table if exists oengine cascade;

drop table if exists ogear_box cascade;

drop table if exists omvertex cascade;

drop table if exists omvertex_other cascade;

drop table if exists oroad_show_msg cascade;

drop table if exists om_account_child_dbo cascade;

drop table if exists om_account_dbo cascade;

drop table if exists om_basic_child cascade;

drop table if exists om_basic_parent cascade;

drop table if exists om_ordered_detail cascade;

drop table if exists om_ordered_master cascade;

drop table if exists oml_bar cascade;

drop table if exists oml_baz cascade;

drop table if exists oml_foo cascade;

drop table if exists only_id_entity cascade;

drop table if exists o_order cascade;

drop table if exists o_order_detail cascade;

drop table if exists s_orders cascade;

drop table if exists s_order_items cascade;

drop table if exists order_master cascade;

drop table if exists order_master_inheritance cascade;

drop table if exists order_referenced_parent cascade;

drop table if exists or_order_ship cascade;

drop table if exists order_toy cascade;

drop table if exists ordered_parent cascade;

drop table if exists organisation cascade;

drop table if exists organization_node cascade;

drop table if exists organization_tree_node cascade;

drop table if exists orp_detail cascade;

drop table if exists orp_detail2 cascade;

drop table if exists orp_master cascade;

drop table if exists orp_master2 cascade;

drop table if exists oto_aone cascade;

drop table if exists oto_atwo cascade;

drop table if exists oto_bchild cascade;

drop table if exists oto_bmaster cascade;

drop table if exists oto_child cascade;

drop table if exists oto_cust cascade;

drop table if exists oto_cust_address cascade;

drop table if exists oto_level_a cascade;

drop table if exists oto_level_b cascade;

drop table if exists oto_level_c cascade;

drop table if exists oto_master cascade;

drop table if exists oto_prime cascade;

drop table if exists oto_prime_extra cascade;

drop table if exists oto_sd_child cascade;

drop table if exists oto_sd_master cascade;

drop table if exists oto_th_many cascade;

drop table if exists oto_th_one cascade;

drop table if exists oto_th_top cascade;

drop table if exists oto_ubprime cascade;

drop table if exists oto_ubprime_extra cascade;

drop table if exists oto_uprime cascade;

drop table if exists oto_uprime_extra cascade;

drop table if exists oto_user_model cascade;

drop table if exists oto_user_model_optional cascade;

drop table if exists pfile cascade;

drop table if exists pfile_content cascade;

drop table if exists paggview cascade;

drop table if exists pallet_location cascade;

drop table if exists parcel cascade;

drop table if exists parcel_location cascade;

drop table if exists rawinherit_parent cascade;

drop table if exists rawinherit_parent_rawinherit_data cascade;

drop table if exists e_save_test_c cascade;

drop table if exists parent_person cascade;

drop table if exists c_participation cascade;

drop table if exists password_store_model cascade;

drop table if exists pcf_calendar cascade;

drop table if exists pcf_city cascade;

drop table if exists pcf_country cascade;

drop table if exists pcf_event cascade;

drop table if exists pcf_person cascade;

drop table if exists mt_permission cascade;

drop table if exists persistent_file cascade;

drop table if exists persistent_file_content cascade;

drop table if exists person cascade;

drop table if exists persons cascade;

drop table if exists person_cache_email cascade;

drop table if exists person_cache_info cascade;

drop table if exists phones cascade;

drop table if exists e_position cascade;

drop table if exists primary_revision cascade;

drop table if exists o_product cascade;

drop table if exists pp cascade;

drop table if exists pp_to_ww cascade;

drop table if exists question cascade;

drop table if exists rcustomer cascade;

drop table if exists r_orders cascade;

drop table if exists referenced_defaults_model cascade;

drop table if exists referenced_defaults_model_draft cascade;

drop table if exists referencing_bean cascade;

drop table if exists region cascade;

drop table if exists rel_detail cascade;

drop table if exists rel_master cascade;

drop table if exists resourcefile cascade;

drop table if exists mt_role cascade;

drop table if exists mt_role_permission cascade;

drop table if exists em_role cascade;

drop table if exists root_bean cascade;

drop table if exists f_second cascade;

drop table if exists section cascade;

drop table if exists self_parent cascade;

drop table if exists self_ref_customer cascade;

drop table if exists self_ref_example cascade;

drop table if exists e_save_test_a cascade;

drop table if exists e_save_test_b cascade;

drop table if exists site cascade;

drop table if exists site_address cascade;

drop table if exists some_enum_bean cascade;

drop table if exists some_file_bean cascade;

drop table if exists some_new_types_bean cascade;

drop table if exists some_period_bean cascade;

drop table if exists source_base cascade;

drop table if exists stockforecast cascade;

drop table if exists sub_section cascade;

drop table if exists sub_type cascade;

drop table if exists survey cascade;

drop table if exists tbytes_only cascade;

drop table if exists tcar cascade;

drop table if exists tevent cascade;

drop table if exists tevent_many cascade;

drop table if exists tevent_one cascade;

drop table if exists tint_root cascade;

drop table if exists tjoda_entity cascade;

drop table if exists t_mapsuper1 cascade;

drop table if exists t_oneb cascade;

drop table if exists t_detail_with_other_namexxxyy cascade;
drop sequence if exists t_atable_detail_seq;

drop table if exists t_atable_thatisrelatively cascade;
drop sequence if exists t_atable_master_seq;

drop table if exists ttruck_holder cascade;

drop table if exists ttruck_holder_item cascade;

drop table if exists tuuid_entity cascade;

drop table if exists twheel cascade;

drop table if exists twith_pre_insert cascade;

drop table if exists target_base cascade;

drop table if exists mt_tenant cascade;

drop table if exists test_annotation_base_entity cascade;

drop table if exists tire cascade;
drop sequence if exists tire_seq;

drop table if exists sa_tire cascade;
drop sequence if exists sa_tire_seq;

drop table if exists tree_entity cascade;

drop table if exists trip cascade;

drop table if exists truck_ref cascade;

drop table if exists tune cascade;

drop table if exists "type" cascade;

drop table if exists tz_bean cascade;

drop table if exists usib_child cascade;

drop table if exists usib_child_sibling cascade;

drop table if exists usib_parent cascade;

drop table if exists ut_detail cascade;

drop table if exists ut_master cascade;

drop table if exists uuone cascade;

drop table if exists uutwo cascade;

drop table if exists oto_user cascade;

drop trigger if exists c_user_history_upd on c_user cascade;
drop function if exists c_user_history_version();

drop view c_user_with_history;
alter table c_user drop column sys_period;
drop table c_user_history;

drop table if exists c_user cascade;

drop table if exists tx_user cascade;

drop table if exists g_user cascade;

drop table if exists em_user cascade;

drop table if exists user_interest_live cascade;

drop table if exists em_user_role cascade;

drop table if exists vehicle cascade;

drop table if exists vehicle_driver cascade;

drop table if exists vehicle_lease cascade;

drop table if exists version_child cascade;

drop table if exists version_parent cascade;

drop table if exists version_toy cascade;

drop table if exists warehouses cascade;

drop table if exists warehousesshippingzones cascade;

drop table if exists wheel cascade;
drop sequence if exists wheel_seq;

drop table if exists sa_wheel cascade;
drop sequence if exists sa_wheel_seq;

drop table if exists sp_car_wheel cascade;
drop sequence if exists sp_car_wheel_seq;

drop table if exists g_who_props_otm cascade;

drop table if exists with_zero cascade;

drop table if exists parent cascade;

drop table if exists wview cascade;

drop table if exists zones cascade;

drop index if exists ix_contact_last_name_first_name;
drop index if exists ix_e_basic_name;
drop index if exists ix_efile2_no_fk_owner_id;
drop index if exists ix_ecsm_values_host_id;
drop index if exists ix_order_referenced_parent_type;
drop index if exists ix_organization_node_kind;
drop index concurrently if exists ix_t_detail_with_other_namexxxyy_lowername;
drop index if exists ix_t_detail_with_other_namexxxyy_defn;
drop index if exists ano_3;
drop index if exists ano_1;
drop index if exists ano_2;
