package io.ebeaninternal.dbmigration.ddlgeneration.platform;

import io.ebean.config.dbplatform.DatabasePlatform;
import io.ebeaninternal.dbmigration.ddlgeneration.DdlBuffer;
import java.util.ArrayList;
import java.util.List;

import io.ebean.util.StringHelper;
import io.ebeaninternal.dbmigration.ddlgeneration.DdlAlterTable;
import io.ebeaninternal.dbmigration.ddlgeneration.DdlWrite;
import io.ebeaninternal.dbmigration.migration.Column;

/**
 * DB2 platform specific DDL.
 * 
 * according to the list
 * https://datageek.blog/en/2014/05/06/db2-basics-what-is-a-reorg/ a reorg is
 * necessary after
 * <ol>
 * <li>Data type changes that increase the size of a varchar or vargraphic
 * column
 * <li>Data type changes that decrease the size of a varchar or vargraphic
 * column
 * <li>Altering a column to include NOT NULL
 * <li>Altering a column to inline LOBS
 * <li>Altering a column to compress the system default or turn off compression
 * for the system default
 * <li>Altering a table to enable value compression
 * <li>Altering a table to drop a column
 * <li>Changing the PCTFREE for a table
 * <li>Altering a table to turn APEND mode off
 * <li>Altering a table or index to turn compression on
 * </ol>
 * 
 * This is currently handled by BaseTableDdl
 * 
 */
public class DB2Ddl extends PlatformDdl {
  private static final String MOVE_TABLE = "CALL SYSPROC.ADMIN_MOVE_TABLE(CURRENT_SCHEMA,'%s','%s','%s','%s','','','','','','MOVE')";

  public DB2Ddl(DatabasePlatform platform) {
    super(platform);
    this.dropTableIfExists = "drop table ";
    this.dropSequenceIfExists = "drop sequence ";
    this.dropConstraintIfExists = "NOT USED";
    this.dropIndexIfExists = "NOT USED";
    this.identitySuffix = " generated by default as identity";
    this.columnSetNull = "drop not null";
    this.columnSetType = "set data type ";
    this.inlineUniqueWhenNullable = false;
    this.historyDdl = new Db2HistoryDdl();
  }

  @Override
  public String alterTableTablespace(String tablename, String tableSpace, String indexSpace, String lobSpace) {
    if(tableSpace == null) {
      // if no tableSpace set, use the default tablespace USERSPACE1
      return String.format(MOVE_TABLE, tablename.toUpperCase(), "USERSPACE1", "USERSPACE1", "USERSPACE1");
    } else {
      return String.format(MOVE_TABLE, tablename.toUpperCase(), tableSpace, indexSpace, lobSpace);
    }
  }
  
  @Override
  public String alterTableAddUniqueConstraint(String tableName, String uqName, String[] columns,
      String[] nullableColumns) {
    StringBuilder sb = new StringBuilder(300);
    if (nullableColumns == null || nullableColumns.length == 0) {

      sb.append("alter table ").append(lowerTableName(tableName));
      sb.append(" add constraint ").append(maxConstraintName(uqName)).append(" unique ");
      appendColumns(columns, sb);
      return sb.toString();
    }

    if (uqName == null) {
      throw new NullPointerException();
    }
    sb = new StringBuilder("create unique index ");
    sb.append(maxConstraintName(uqName)).append(" on ").append(tableName).append('(');

    for (int i = 0; i < columns.length; i++) {
      if (i > 0) {
        sb.append(",");
      }
      sb.append(lowerColumnName(columns[i]));
    }
    sb.append(") exclude null keys");
    return sb.toString();
  }


  //  @Override
  //  public void addTablespace(DdlBuffer apply, String tablespaceName, String indexTablespace, String lobTablespace)
  //      throws IOException {
  //    apply.append(" in ").append(tablespaceName).append(" index in ").append(indexTablespace).append(" long in ").append(lobTablespace);
  //  }
  
  @Override
  public void alterTableAddColumn(DdlWrite writer, String tableName, Column column, boolean onHistoryTable, String defaultValue) {

    String convertedType = convert(column.getType());
    DdlBuffer buffer = alterTable(writer, tableName).append(addColumn, column.getName());
    buffer.append(convertedType);

    // Add default value also to history table if it is not excluded
    if (defaultValue != null) {
      buffer.append(" default ");
      buffer.append(defaultValue);
    }

    if (isTrue(column.isNotnull())) {
      buffer.appendWithSpace(columnNotNull);
    }
    // DB2 History table must match exact!
    if (!onHistoryTable) {
      // check constraints cannot be added in one statement for h2
      if (!StringHelper.isNull(column.getCheckConstraint())) {
        String ddl = alterTableAddCheckConstraint(tableName, column.getCheckConstraintName(), column.getCheckConstraint());
        writer.applyPostAlter().appendStatement(ddl);
      }
    }

  }
  @Override
  public String alterTableDropForeignKey(String tableName, String fkName) {
    return alterTableDropConstraint(tableName, fkName);
  };

  @Override
  public String alterTableDropUniqueConstraint(String tableName, String uniqueConstraintName) {
    return alterTableDropConstraint(tableName, uniqueConstraintName)
      + "\n" + dropIndex(uniqueConstraintName, tableName);
  }

  @Override
  public String alterTableDropConstraint(String tableName, String constraintName) {
    StringBuilder sb = new StringBuilder(300);
    sb.append("delimiter $$\n")
      .append("begin\n")
      .append("if exists (select constname from syscat.tabconst where tabschema = current_schema and constname = '")
      .append(maxConstraintName(constraintName).toUpperCase())
      .append("' and tabname = '").append(lowerTableName(tableName).toUpperCase()).append("') then\n")

      .append("  prepare stmt from 'alter table ").append(lowerTableName(tableName))
      .append(" drop constraint ").append(maxConstraintName(constraintName)).append("';\n")

      .append("  execute stmt;\n")
      .append("end if;\n")
      .append("end$$");
    return sb.toString();

  }

  @Override
  public String dropIndex(String indexName, String tableName, boolean concurrent) {
    StringBuilder sb = new StringBuilder(300);
    sb.append("delimiter $$\n")
      .append("begin\n")
      .append("if exists (select indname from syscat.indexes where indschema = current_schema and indname = '")
      .append(maxConstraintName(indexName).toUpperCase()).append("') then\n")
      .append("  prepare stmt from 'drop index ").append(maxConstraintName(indexName)).append("';\n")
      .append("  execute stmt;\n")
      .append("end if;\n")
      .append("end$$");
    return sb.toString();
  }

  @Override
  public String dropSequence(String sequenceName) {
    StringBuilder sb = new StringBuilder(300);
    sb.append("delimiter $$\n");
    sb.append("begin\n");
    sb.append("if exists (select seqschema from syscat.sequences where seqschema = current_schema and seqname = '")
      .append(maxConstraintName(sequenceName).toUpperCase()).append("') then\n");
    sb.append("  prepare stmt from 'drop sequence ").append(maxConstraintName(sequenceName)).append("';\n");
    sb.append("  execute stmt;\n");
    sb.append("end if;\n");
    sb.append("end$$");
    return sb.toString();
  }

@Override
protected DdlAlterTable alterTable(DdlWrite writer, String tableName) {
  return writer.applyAlterTable(tableName, Db2AlterTableWrite::new);
};
  static class Db2AlterTableWrite extends BaseAlterTableWrite {

    public Db2AlterTableWrite(String tableName) {
      super(tableName);
    }

    @Override
    protected List<AlterCmd> postProcessCommands(List<AlterCmd> cmds) {
      List<AlterCmd> ret = new ArrayList<>(cmds.size() + 1);
      boolean requiresReorg = false;
      for (AlterCmd cmd : cmds) {
        ret.add(cmd);
        if (!requiresReorg && checkReorg(cmd)) {
          requiresReorg = true;
        }
      }
      if (requiresReorg) {
        ret.add(newRawCommand("call sysproc.admin_cmd('reorg table " + tableName() + "')"));
      }
      return ret;
    }

    /**
     * determine, if we need a reorg.
     * 
     * See: https://www.ibm.com/docs/en/db2/11.5?topic=statements-alter-table The following is the full list of REORG-recommended
     * ALTER statements that cause a version change and place the table into a REORG-pending state:
     * <ul>
     * <li>DROP COLUMN
     * <li>ALTER COLUMN SET NOT NULL
     * <li>ALTER COLUMN DROP NOT NULL
     * <li>ALTER COLUMN SET DATA TYPE, except in the following situations:<br>
     * Increasing the length of a VARCHAR or VARGRAPHIC column<br>
     * Decreasing the length of a VARCHAR or VARGRAPHIC column without truncating trailing blanks from existing data, when no indexes
     * exist on the column
     * </ul>
     * 
     */
    private boolean checkReorg(AlterCmd cmd) {
      switch (cmd.getOperation()) {
      case "drop column":
        return true;
      case "alter column":
        String alter = cmd.getAlternation();
        return alter.equals("set not null")
          || alter.equals("drop not default")
          || alter.startsWith("set data type"); // note: altering varchar length only is not detected here
      default:
        return false;
      }
    }
  }
}
