#!/bin/sh

echo "\n=== SETUP DATABASE ===\n"

set -e
set -x

# Setup postgres' users and databases
sudo -u postgres psql -c "CREATE USER unit WITH PASSWORD 'unit';"
sudo -u postgres psql -c 'CREATE DATABASE test WITH OWNER unit;'
sudo -u postgres psql test -c 'CREATE EXTENSION hstore;'
sudo -u postgres psql test -c 'CREATE EXTENSION pgcrypto;'
sudo -u postgres psql test -c 'CREATE EXTENSION postgis;'

