ebean.test.platform=oracle
ebean.test.dbName=test_eb
datasource.default=oracle
ebean.lengthCheck=utf8
datasource.oracle.pstmtCacheSize=50
datasource.oracle.maxConnections=20
datasource.oracle-ro.pstmtCacheSize=50
