package io.ebeaninternal.dbmigration.ddlgeneration.platform;

import io.ebean.config.dbplatform.DatabasePlatform;

/**
 * Hsqldb platform specific DDL.
 */
public class HsqldbDdl extends PlatformDdl {

  public HsqldbDdl(DatabasePlatform platform) {
    super(platform);
    this.identitySuffix = " generated by default as identity (start with 1) ";
  }

}
