package org.tests.dtomapping;

import io.ebean.DB;
import org.junit.jupiter.api.Test;
import org.tests.dtomapping.model.Address;
import org.tests.dtomapping.model.Customer;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Isolated test for the generated {@code AddressDtoMapper} - validates it can be used standalone,
 * independent of {@code CustomerDtoMapper}, confirming the per-type mapper composition approach.
 * The mapper itself is generated by {@code querybean-generator} from the {@code @DtoMapping}
 * registered in {@code package-info.java} - see docs/dto-mapping-design.md (requirement
 * dto-codegen-mapper).
 */
class TestAddressDtoMapping {

  private final AddressDtoMapper mapper = new AddressDtoMapper();

  @Test
  void mapAddress_expectFieldsCopied() {
    Address address = new Address("12 Test Street", "Auckland");
    address.save();

    Customer customer = new Customer("Acme");
    customer.setBillingAddress(address);
    customer.save();

    Customer found = DB.find(Customer.class)
      .setUnmodifiable(true)
      .fetch("billingAddress", "id,line1,city")
      .where().idEq(customer.getId())
      .findOne();

    AddressDto dto = mapper.map(found.getBillingAddress());

    assertThat(dto.getId()).isEqualTo(address.getId());
    assertThat(dto.getLine1()).isEqualTo(address.getLine1());
    assertThat(dto.getCity()).isEqualTo(address.getCity());
  }

  @Test
  void mapAddress_whenNull_expectNull() {
    assertThat(mapper.map(null)).isNull();
  }
}
