package org.tests.dtomapping;

import io.ebean.DB;
import io.ebean.LazyInitialisationException;
import org.junit.jupiter.api.Test;
import org.tests.dtomapping.model.Address;
import org.tests.dtomapping.model.Contact;
import org.tests.dtomapping.model.Customer;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end validation of the generated nested (ToOne + ToMany) DTO graph mapping for issue
 * #2540 - the key milestone for requirement dto-codegen-mapper: {@code CustomerDtoMapper} (and
 * its nested {@code AddressDtoMapper}/{@code ContactDtoMapper}/{@code CustomerRefDtoMapper}) are
 * entirely generated by {@code querybean-generator} from the {@code @DtoMapping} declarations in
 * {@code package-info.java} - no hand-written mapper code exists in this module.
 */
class TestCustomerDtoGraphMapping {

  private final CustomerDtoMapper mapper = new CustomerDtoMapper();

  @Test
  void mapCustomerWithBillingAddress_whenFetched_expectPopulatedDto() {
    Address address = new Address("12 Test Street", "Auckland");
    address.save();

    Customer customer = new Customer("Acme");
    customer.setBillingAddress(address);
    customer.save();
    new Contact("Jane", "Doe", customer).save();
    new Contact("John", "Doe", customer).save();

    List<Customer> customers = DB.find(Customer.class)
      .setUnmodifiable(true)
      .select("id,name")
      .fetch("billingAddress", "id,line1,city")
      .fetch("contacts", "id,firstName,lastName,active,customer")
      .fetch("contacts.customer", "id,name")
      .fetch("contacts.customer.billingAddress", "id,city")
      .where().idEq(customer.getId())
      .findList();

    List<CustomerDto> dtos = mapper.mapList(customers);

    assertThat(dtos).hasSameSizeAs(customers);
    for (int i = 0; i < dtos.size(); i++) {
      Customer source = customers.get(i);
      CustomerDto dto = dtos.get(i);

      assertThat(dto.getId()).isEqualTo(source.getId());
      assertThat(dto.getName()).isEqualTo(source.getName());

      assertThat(dto.getBillingAddress().getId()).isEqualTo(source.getBillingAddress().getId());
      assertThat(dto.getBillingAddress().getLine1()).isEqualTo(source.getBillingAddress().getLine1());
      assertThat(dto.getBillingAddress().getCity()).isEqualTo(source.getBillingAddress().getCity());

      assertThat(dto.getContacts()).hasSameSizeAs(source.getContacts());
      for (int c = 0; c < dto.getContacts().size(); c++) {
        assertThat(dto.getContacts().get(c).getFirstName()).isEqualTo(source.getContacts().get(c).getFirstName());
        // the ToMany contact's back-reference resolves to the very same CustomerRefDto instance
        // as every sibling contact under this customer - identity de-dup (requirement r3/r1)
        assertThat(dto.getContacts().get(c).getCustomer().getId()).isEqualTo(dto.getId());
      }
      assertThat(dto.getContacts().get(0).getCustomer()).isSameAs(dto.getContacts().get(1).getCustomer());
    }
  }

  @Test
  void mapCustomer_whenBillingAddressNotFetched_expectFailFastNotSilentNullOrLazyLoad() {
    Customer customer = new Customer("Acme");
    customer.save();

    // deliberately does NOT fetch billingAddress - mismatch between DTO shape and query
    Customer found = DB.find(Customer.class)
      .setUnmodifiable(true)
      .select("id,name")
      .where().idEq(customer.getId())
      .findOne();

    // The generated mapper has no special-case handling for this - it just calls
    // getBillingAddress(), which fails fast because the unmodifiable+disableLazyLoading graph
    // refuses to silently lazy load or return null for an unloaded property. This is the
    // fail-fast guarantee (requirement r7) coming "for free" out of the mapTo pipeline design.
    assertThatThrownBy(() -> mapper.map(found))
      .isInstanceOf(LazyInitialisationException.class)
      .hasMessageContaining("Property not loaded: billingAddress");
  }

  @Test
  void mapCustomer_whenSourceNull_expectNullDto() {
    assertThat(mapper.map(null)).isNull();
  }
}
